### ISSUE TITLE
compile errors

### ISSUE THREAD

**Issue by cfblaeb** [latture/pallas-solver#1]
Hi,
Trying to compile the example in the readme.
I get the following error:
pallas-solver/include/pallas/step_function.h:31:10: fatal error: pallas/internal/random_number_generator.h: No such file or directory

I see several references to pallas/internal, but as far as I can tell no such folder exists.
Also your project depends on rapidjson.

**Comment by latture** [comment]
The files you're referring to are in the `src/pallas/internal` directory. I left the headers for internal files there to follow the conventions used in Ceres solver (since most of Pallas is based on their code). Adding `src/pallas/internal` to your include path should solve your problem. A list of all required include directories are given in the top level CMakeLists.txt if you find other files are missing.

Rapidjson is used track the optimization. (The optimization history is stored using a series of JSON objects.)
